
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import VeilContractArtifactJson from '../target/bob_token_contract-Veil.json' with { type: 'json' };
export const VeilContractArtifact = loadContractArtifact(VeilContractArtifactJson as NoirCompiledContract);


      export type Withdrawal = {
        recipient: AztecAddressLike
amount: (bigint | number)
block_number: (bigint | number)
      }
    

      export type AuditRequested = {
        target_user: AztecAddressLike
reason_hash: FieldLike
block_number: (bigint | number)
      }
    

/**
 * Type-safe interface for contract Veil;
 */
export class VeilContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, VeilContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): VeilContract {
    return Contract.at(address, VeilContract.artifact, wallet) as VeilContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, initial_owner: AztecAddressLike, initial_auditor: AztecAddressLike, initial_approved_list_root: FieldLike, initial_transfer_threshold: (bigint | number)) {
    return new DeployMethod<VeilContract>(PublicKeys.default(), wallet, VeilContractArtifact, (instance, wallet) => VeilContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, initial_owner: AztecAddressLike, initial_auditor: AztecAddressLike, initial_approved_list_root: FieldLike, initial_transfer_threshold: (bigint | number)) {
    return new DeployMethod<VeilContract>(publicKeys, wallet, VeilContractArtifact, (instance, wallet) => VeilContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof VeilContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<VeilContract['methods'][M]>
  ) {
    return new DeployMethod<VeilContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      VeilContractArtifact,
      (instance, wallet) => VeilContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return VeilContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(VeilContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'owner' | 'auditor' | 'private_balances' | 'audit_keys' | 'approved_list_root' | 'transfer_threshold' | 'deposit_counter' | 'deposit_receipts'> {
      return {
        owner: {
      slot: new Fr(1n),
    },
auditor: {
      slot: new Fr(2n),
    },
private_balances: {
      slot: new Fr(3n),
    },
audit_keys: {
      slot: new Fr(4n),
    },
approved_list_root: {
      slot: new Fr(5n),
    },
transfer_threshold: {
      slot: new Fr(6n),
    },
deposit_counter: {
      slot: new Fr(7n),
    },
deposit_receipts: {
      slot: new Fr(8n),
    }
      } as ContractStorageLayout<'owner' | 'auditor' | 'private_balances' | 'audit_keys' | 'approved_list_root' | 'transfer_threshold' | 'deposit_counter' | 'deposit_receipts'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor(initial_owner: struct, initial_auditor: struct, initial_approved_list_root: field, initial_transfer_threshold: integer) */
    constructor: ((initial_owner: AztecAddressLike, initial_auditor: AztecAddressLike, initial_approved_list_root: FieldLike, initial_transfer_threshold: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_approved_list_root() */
    get_approved_list_root: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_auditor() */
    get_auditor: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_deposit_counter() */
    get_deposit_counter: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_deposit_receipt(deposit_id: integer) */
    get_deposit_receipt: ((deposit_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_owner() */
    get_owner: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_transfer_threshold() */
    get_transfer_threshold: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_registered(user: struct) */
    is_registered: ((user: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** mint(recipient: struct, amount: integer) */
    mint: ((recipient: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** private_balance_of(owner: struct) */
    private_balance_of: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** private_transfer(recipient: struct, amount: integer, innocence_proof: struct) */
    private_transfer: ((recipient: AztecAddressLike, amount: (bigint | number), innocence_proof: { deposit_id: (bigint | number), siblings: FieldLike[], leaf_index: (bigint | number) }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_for_audit(encrypted_key: array) */
    register_for_audit: ((encrypted_key: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** request_audit(target_user: struct, reason_hash: field) */
    request_audit: ((target_user: AztecAddressLike, reason_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** rotate_audit_key(new_encrypted_key: array) */
    rotate_audit_key: ((new_encrypted_key: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** update_approved_list_root(new_root: field) */
    update_approved_list_root: ((new_root: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** update_transfer_threshold(new_threshold: integer) */
    update_transfer_threshold: ((new_threshold: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** withdraw_to_public(amount: integer, recipient: struct, innocence_proof: struct) */
    withdraw_to_public: ((amount: (bigint | number), recipient: AztecAddressLike, innocence_proof: { deposit_id: (bigint | number), siblings: FieldLike[], leaf_index: (bigint | number) }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
    public static get events(): { Withdrawal: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, AuditRequested: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      Withdrawal: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "recipient",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "amount",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 64
            }
        },
        {
            "name": "block_number",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 32
            }
        }
    ],
    "path": "Veil::Withdrawal"
},
        eventSelector: EventSelector.fromString("0x37ffc5c0"),
        fieldNames: ["recipient","amount","block_number"],
      },
AuditRequested: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "target_user",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "reason_hash",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "block_number",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 32
            }
        }
    ],
    "path": "Veil::AuditRequested"
},
        eventSelector: EventSelector.fromString("0xd85b432d"),
        fieldNames: ["target_user","reason_hash","block_number"],
      }
    };
  }
  
}
